[theme]
primaryColor = "#e91e63"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"

[server]
maxUploadSize = 200
enableXsrfProtection = true

[browser]
gatherUsageStats = false 